[project]
authors = ["Katherine Rosenfeld <56368533+krosenfeld-IDM@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "workspace"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
